npm init -y
npm install webpack webpack-cli babel-loader @babel/core @babel/preset-env @babel/preset-react --save-dev
const path = require('path');

module.exports = {
  entry: './index.tsx', // مسیر فایل اصلی TSX شما
  output: {
    path: path.resolve(__dirname, 'dist'), // پوشه خروجی
    filename: 'bundle.js', // نام فایل خروجی
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx|ts|tsx)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env', '@babel/preset-react', "@babel/preset-typescript"],
          },
        },
      },
    ],
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js', '.jsx'],
  },
  mode: 'development', // یا 'production' برای محیط تولید
};
{
  "presets": ["@babel/preset-env", "@babel/preset-react", "@babel/preset-typescript"]
}
"scripts": {
  "build": "webpack"
}
npm run build
